### ISSUE TITLE
constant p0

### ISSUE THREAD

**Issue by kls2177** [mjucker/aostools#6] opened 2021-07-19 17:39 UTC
Hi Martin, I have been playing around with the "ComputeMeridionalPVGrad" function and I think the call to the .constants module may be slightly off. The call says "import p0_Pa as p0" but I think it should just be "p0". Thanks!

**Comment by mjucker** [comment] 2021-09-24 04:19
Hi Karen, thanks heaps for letting me know (and sorry for the slow response). This has been fixed with commit 2c5a17835fe3411b234bf884706acc4ffc2c75bd . Hope `aostools` is helpful!

**Comment by mjucker** [comment] 2021-09-24 04:43
...actually, it should be in Pa, not hPa (note conversion to Pa of p). So this should really be fixed with commit 583cc5e. If you get to it, maybe you could test to confirm?

**Comment by kls2177** [comment] 2021-09-24 13:06
Hi Martin, thanks. It doesn't seem to be working for me right now after I upgraded aostools. I am getting the following error:
ImportError: cannot import name 'p0_Pa' from 'aostools.constants'.

When I look at the list of constants available with I import the constants package alone, I do not see p0_Pa, only p0.

Just another note, I think this fix also needs to apply to the XR version of the code as well.

**Comment by mjucker** [comment] 2021-09-24 21:31
Hi Karen. I can't reproduce the problem now. Are you sure you've got the latest commits? The `p0_Pa` variable is here https://github.com/mjucker/aostools/blob/9e895bb0963ab7e384f51312ba0f5681f52c3589/constants.py#L13 . This is not needed in the Xr version as I don't convert pressure to Pa.

**Comment by mjucker** [comment] 2021-10-19 09:20
Hi Karen, does this work for you now?

**Comment by mjucker** [comment] 2022-02-24 00:50
closing this. feel free to re-open if not resolved.

**Closed as completed by mjucker** 2022-02-24 00:50 UTC
